spring.application.name=gatewayServer
server.port=8765

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=${spring.application.name}:${server.port}

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true



logging.file.name=/Users/mohantyrohan3/Rohan/Projects/Java_Projects/Recurring Notification System/logs/${spring.application.name}.log